### ISSUE TITLE
testsuite fails with ruby 3.4.0dev

### ISSUE THREAD

**Issue by mtasaka** [mvidner/ruby-dbus#144]
ruby 3.4 is to be released on 2024-Dec-25, and trying with `ruby 3.4.0dev (2024-12-20 master 978df259ca) +PRISM [x86_64-linux]` : 
https://github.com/ruby/ruby/commit/978df259ca90c25ca2acb95a099ff6d3ff0161b0
(perhaps as well as ruby 3.4.0 rc1),

Trying ruby-dbus git head ( https://github.com/mvidner/ruby-dbus/commit/5f98ee3cf506ff0bd53b72ce952b1b89881ab64a ) rspec testsuite fails like:

```
[mockbuild@acda33e8d75943d4bbbee7418ed991a6 ruby-dbus]$ spec/tools/test_env rspec spec

Failures:

  1) ErrMsgTest tests report dbus interface
     Failure/Error:
       expect { @obj.NoSuchMethod }
         .to raise_error(NameError, /DBus interface.*#{@obj.default_iface}/)
     
       expected NameError with message matching /DBus interface.*org.ruby.SampleInterface/, got #<NameError: undefined method 'NoSuchMethod' for class '#<Class:#<DBus::ProxyObjectInterface:0x00007f066720af20>>'> with backtrace:
         # ./lib/dbus/proxy_object.rb:158:in 'Kernel#method'
         # ./lib/dbus/proxy_object.rb:158:in 'DBus::ProxyObject#method_missing'
         # ./spec/err_msg_spec.rb:20:in 'block (3 levels) in <top (required)>'
         # ./spec/err_msg_spec.rb:21:in 'block (2 levels) in <top (required)>'
     # ./spec/err_msg_spec.rb:21:in 'block (2 levels) in <top (required)>'

Finished in 50.63 seconds (files took 0.71689 seconds to load)
1090 examples, 1 failure

Failed examples:

rspec ./spec/err_msg_spec.rb:17 # ErrMsgTest tests report dbus interface
```

**Comment by mtasaka** [comment]
This is because ruby3.4 changes backtrace format:
https://github.com/ruby/ruby/blob/978df259ca90c25ca2acb95a099ff6d3ff0161b0/NEWS.md?plain=1#L334-L352

especially, opening quote changes from backtick to single quote.  
So this regex does not match and then raises the error as it is:
https://github.com/mvidner/ruby-dbus/blob/5f98ee3cf506ff0bd53b72ce952b1b89881ab64a/lib/dbus/proxy_object.rb#L162

while what is expected is that this line is executed and raise exception:
https://github.com/mvidner/ruby-dbus/blob/5f98ee3cf506ff0bd53b72ce952b1b89881ab64a/lib/dbus/proxy_object.rb#L165
