### ISSUE TITLE
AltLinux: Connection refused - connect(2) 

### ISSUE THREAD

**Issue by majioa** [mvidner/ruby-dbus#60]
I have the following trouble in the connection to Session bus:

```
/usr/local/home/majioa/git/ntp/lib/ntp/server/control.rb:53:in `get_connection'/usr/local/home/majioa/git/ntp/.bundle/gems/ruby-dbus-0.11.0/lib/dbus/message_queue.rb:115:in `connect': Connection refused - connect(2) for UNIX:00:2f:76:61:72:2f:72:75:6e:2f:64:62:75:73:2f:75:73:65:72:73:2f:64:62:75:73:2d:54:67:4c:79:6f:51:4b:67:71:37 (Errno::ECONNREFUSED)
from /usr/local/home/majioa/git/ntp/.bundle/gems/ruby-dbus-0.11.0/lib/dbus/message_queue.rb:115:in `connect_to_unix'
```

code:

```
bus = DBus::SessionBus.instance
```

how to fix it?

**Comment by mvidner** [comment]
Sorry for the delay.
What platform are you using?
Are you trying to connect to a user's session bus as root, or as another user?
On my openSUSE 13.2 for example, that fails (with a different error)
```console
# echo $DBUS_SESSION_BUS_ADDRESS 
unix:abstract=/tmp/dbus-1CeDOgowXD,guid=7991da599df22e69c4463e635727761d
# ruby -rdbus -e 'DBus::SessionBus.instance'
/usr/lib64/ruby/gems/2.1.0/gems/ruby-dbus-0.11.0/lib/dbus/message_queue.rb:46:in `write': Broken pipe (Errno::EPIPE)
        from /usr/lib64/ruby/gems/2.1.0/gems/ruby-dbus-0.11.0/lib/dbus/message_queue.rb:46:in `push'
        from /usr/lib64/ruby/gems/2.1.0/gems/ruby-dbus-0.11.0/lib/dbus/bus.rb:442:in `send_sync'
        from /usr/lib64/ruby/gems/2.1.0/gems/ruby-dbus-0.11.0/lib/dbus/bus.rb:582:in `send_hello'
        from /usr/lib64/ruby/gems/2.1.0/gems/ruby-dbus-0.11.0/lib/dbus/bus.rb:601:in `initialize'
        from /usr/lib64/ruby/2.1.0/singleton.rb:141:in `new'
        from /usr/lib64/ruby/2.1.0/singleton.rb:141:in `block in instance'
        from /usr/lib64/ruby/2.1.0/singleton.rb:139:in `synchronize'
        from /usr/lib64/ruby/2.1.0/singleton.rb:139:in `instance'
```

**Comment by majioa** [comment]
@mvidner I have AltLinux.

**Comment by mvidner** [comment]
Thanks!
I've tried to reproduce the problem on an AltLinux system but so far without success:
The liveCD ftp://distrib-coffee.ipsl.jussieu.fr/pub/linux/altlinux/p7/images/centaurus/altlinux-7.0.5-centaurus-x86_64-ru-live-cd.iso has no Ruby, even no GCC to install it via RVM, and I am not familiar enough with apt-rpm to install it.
Anyway, it looks like the bug is dependent on a particular desktop environment you are using. Which version of which DE is it?

**Comment by mvidner** [comment]
Ping?
