### ISSUE TITLE
EOFError in introspect (when using an invalid object path)

### ISSUE THREAD

**Issue by insilmaril** [mvidner/ruby-dbus#80]
Since a while I cannot connect any longer to my own Qt app, probably with new Qt in openSUSE 15.0, just reproduced also in 15.1. 

```
#!/usr/bin/env ruby    
require 'dbus'

@dbus = DBus::SessionBus.instance

# Try out running applications, originally vym, also with konsole. Found via qdbusviewer:
#name = 'org.insilmaril.vym-10982'
name = 'org.kde.konsole-2393'

vym_service = @dbus[name]
vym_obj = vym_service[name]

vym_obj.introspect
```

Results in 
```
Traceback (most recent call last):
        9: from ./dbus-test.rb:18:in `<main>'
        8: from /usr/lib64/ruby/gems/2.5.0/gems/ruby-dbus-0.14.0/lib/dbus/proxy_object.rb:73:in `introspect'
        7: from /usr/lib64/ruby/gems/2.5.0/gems/ruby-dbus-0.14.0/lib/dbus/bus.rb:365:in `introspect_data'
        6: from /usr/lib64/ruby/gems/2.5.0/gems/ruby-dbus-0.14.0/lib/dbus/bus.rb:339:in `send_sync_or_async'
        5: from /usr/lib64/ruby/gems/2.5.0/gems/ruby-dbus-0.14.0/lib/dbus/bus.rb:453:in `send_sync'
        4: from /usr/lib64/ruby/gems/2.5.0/gems/ruby-dbus-0.14.0/lib/dbus/bus.rb:441:in `wait_for_message'
        3: from /usr/lib64/ruby/gems/2.5.0/gems/ruby-dbus-0.14.0/lib/dbus/message_queue.rb:30:in `pop'
        2: from /usr/lib64/ruby/gems/2.5.0/gems/ruby-dbus-0.14.0/lib/dbus/message_queue.rb:154:in `buffer_from_socket_nonblock'
        1: from /usr/lib64/ruby/2.5.0/socket.rb:452:in `read_nonblock'
/usr/lib64/ruby/2.5.0/socket.rb:452:in `__read_nonblock': end of file reached (EOFError)
```

Any hints?
Thx

**Comment by tobias-grasse** [comment]
Hitting the same error in a simple test ruby script using ruby-bus 0.15.0 on an Ubuntu 19.04 machine running ruby 2.6.4 (snap). I want to add a listener for NetworkManager's StateChanged signal:

```ruby
require 'dbus'

sysbus = DBus.system_bus
nm_s = sysbus["org.freedesktop.NetworkManager"]
nm_o = nm_s["org/freedesktop/NetworkManager"]
nm_i = nm_o["org.freedesktop.NetworkManager"]

nm_i.on_signal("StateChanged" do |u|
  puts u
end
```

Results in 
```
Traceback (most recent call last):
	10: from main.rb:6:in `<main>'
	 9: from /home/tobi/.gem/gems/ruby-dbus-0.15.0/lib/dbus/proxy_object.rb:56:in `[]'
	 8: from /home/tobi/.gem/gems/ruby-dbus-0.15.0/lib/dbus/proxy_object.rb:75:in `introspect'
	 7: from /home/tobi/.gem/gems/ruby-dbus-0.15.0/lib/dbus/bus.rb:365:in `introspect_data'
	 6: from /home/tobi/.gem/gems/ruby-dbus-0.15.0/lib/dbus/bus.rb:339:in `send_sync_or_async'
	 5: from /home/tobi/.gem/gems/ruby-dbus-0.15.0/lib/dbus/bus.rb:458:in `send_sync'
	 4: from /home/tobi/.gem/gems/ruby-dbus-0.15.0/lib/dbus/bus.rb:441:in `wait_for_message'
	 3: from /home/tobi/.gem/gems/ruby-dbus-0.15.0/lib/dbus/message_queue.rb:30:in `pop'
	 2: from /home/tobi/.gem/gems/ruby-dbus-0.15.0/lib/dbus/message_queue.rb:154:in `buffer_from_socket_nonblock'
	 1: from /snap/ruby/151/lib/ruby/2.6.0/socket.rb:452:in `read_nonblock'
/snap/ruby/151/lib/ruby/2.6.0/socket.rb:452:in `__read_nonblock': end of file reached (EOFError)
```

If you follow the trace to [this line](https://github.com/mvidner/ruby-dbus/blob/336f1871bf0f6a0669391fb2bcf7f3a003ec97c9/lib/dbus/bus.rb#L441), EOFError seems expected by @mvidner. I'm not sure where to begin debugging this, so any help appreciated.

**Comment by mvidner** [comment]
@tobias-grasse thanks for the report!

An EOFError means that the bus had dropped the connection on us because we have deviated from the protocol, but the bus won't tell us the details because of security.

Here the problem is that the object path is missing the initial slash. This code works for me:

```rb
#!/usr/bin/env ruby    
require 'dbus'

sysbus = DBus.system_bus
nm_s = sysbus["org.freedesktop.NetworkManager"]
# object paths always start with a slash
nm_o = nm_s["/org/freedesktop/NetworkManager"]
nm_i = nm_o["org.freedesktop.NetworkManager"]

nm_i.on_signal("StateChanged") do |u|
  puts u
end

# to act on signals we must run a main loop
main = DBus::Main.new
main << sysbus
main.run
```

**Comment by mvidner** [comment]
@insilmaril your case has the same problem, this fixes the EOFError:
```diff
-vym_service = @dbus[name]
+vym_service = @dbus["/"]
```

**Comment by insilmaril** [comment]
Hi Martin, thanks for looking into this :-) 

Unfortunatly it doesn't fix it for me, still get the EOFError when trying to introspect later.

Just tried this, with a running konsole-1834 instance:

```
#!/usr/bin/env ruby    

require 'dbus'

#name = 'org.insilmaril.vym-10982'
name = "org.kde.konsole-1834"
name2 = "/" + name.gsub(".", "/")

puts name2

bus = DBus::SessionBus.instance

app_s = bus[name]
app_o = app_s[name2]
app_i = app_o[name]
```

The konsole is visible in e.g. in qdbusviewer and introspectable.

(Also fails for my own vym, where I am basically tryining to find the right instance of several running first)

**Comment by mvidner** [comment]
@insilmaril OK, I see.
You seem to be confused by the DBus naming conventions. For many services, like NetworkManager, the service, object, and interface names are the same except the delimiters. But in other cases they are subtly different!

Here the tripping point is that a dash `-` is [not a valid character in an object path](https://dbus.freedesktop.org/doc/dbus-specification.html#message-protocol-marshaling-object-path) after which the bus drops our connection. I need to fix ruby-dbus so that it explains to you what you are doing wrong instead of letting the extremely unfriendly dbus-daemon handle it.

Here's how `qdbus` shows you the correct names:

```console
mvidner@mrakoplas:~$ SVC=$(qdbus | grep vym); echo ===$SVC===
=== org.insilmaril.vym-21165===
mvidner@mrakoplas:~$ qdbus $SVC
/
/vym
/vymmodel_1
mvidner@mrakoplas:~$ qdbus $SVC /vymmodel_1
method QDBusVariant org.insilmaril.vym.model.adaptor.branchCount()
signal void org.insilmaril.vym.model.adaptor.crashed()
method QDBusVariant org.insilmaril.vym.model.adaptor.errorDescription()
method QDBusVariant org.insilmaril.vym.model.adaptor.errorLevel()
method QDBusVariant org.insilmaril.vym.model.adaptor.execute(QString s)
method QDBusVariant org.insilmaril.vym.model.adaptor.getCurrentModelID()
method QDBusVariant org.insilmaril.vym.model.adaptor.listCommands()
method QDBusVariant org.freedesktop.DBus.Properties.Get(QString interface_name, QString property_name)
method QVariantMap org.freedesktop.DBus.Properties.GetAll(QString interface_name)
signal void org.freedesktop.DBus.Properties.PropertiesChanged(QString interface_name, QVariantMap changed_properties, QStringList invalidated_properties)
method void org.freedesktop.DBus.Properties.Set(QString interface_name, QString property_name, QDBusVariant value)
method QString org.freedesktop.DBus.Introspectable.Introspect()
method QString org.freedesktop.DBus.Peer.GetMachineId()
method void org.freedesktop.DBus.Peer.Ping()
mvidner@mrakoplas:~$ qdbus $SVC /vymmodel_1 org.insilmaril.vym.model.adaptor.listCommands
addBranch,addBranchBefore,addMapCenter,addMapInsert,addMapReplace,addSlide,addXLink,branchCount,centerCount,centerOnID,clearFlags,colorBranch,colorSubtree,copy,cut,cycleTask,delete,deleteChildren,deleteKeepChildren,deleteSlide,exportAO,exportASCII,exportCSV,exportHTML,exportImage,exportImpress,exportLast,exportLaTeX,exportOrgMode,exportOrgMode,exportPDF,exportPDF,exportSVG,exportXML,getDestPath,getFileDir,getFrameType,getHeadingPlainText,getHeadingXML,getMapAuthor,getMapComment,getMapTitle,getNotePlainText,getNoteXML,getSelectString,getTaskSleepDays,getURL,getVymLink,getXLinkColor,getXLinkWidth,getXLinkPenStyle,getXLinkStyleBegin,getXLinkStyleEnd,hasActiveFlag,hasNote,hasRichTextNote,hasTask,importDir,isScrolled,loadImage,loadNote,moveDown,moveUp,moveSlideDown,moveSlideUp,move,moveRel,nop,note2URLs,parseVymText,paste,redo,relinkTo,saveImage,saveNote,scroll,select,selectID,selectLastBranch,selectLastImage,selectLatestAdded,selectParent,setFlag,setTaskSleep,setFrameIncludeChildren,setFrameType,setFramePenColor,setFrameBrushColor,setFramePadding,setFrameBorderWidth,setHeadingPlainText,setHideExport,setIncludeImagesHorizontally,setIncludeImagesVertically,setHideLinksUnselected,setMapAnimCurve,setMapAuthor,setMapAnimDuration,setMapBackgroundColor,setMapComment,setMapTitle,setMapDefLinkColor,setMapLinkStyle,setMapRotation,setMapTitle,setMapZoom,setNotePlainText,setScale,setSelectionColor,setURL,setVymLink,setXLinkColor,setXLinkLineStyle,setXLinkStyleBegin,setXLinkStyleEnd,setXLinkWidth,sleep,sortChildren,toggleFlag,toggleFrameIncludeChildren,toggleScroll,toggleTarget,toggleTask,undo,unscroll,unscrollChildren,unselectAll,unsetFlag
```

Here's what happens for invalid and incorrect names:
```console
mvidner@mrakoplas:~$ qdbus $SVC /vymmodel-1 org.insilmaril.vym.model.adaptor.listCommands
Path '/vymmodel-1' is not a valid path name.
mvidner@mrakoplas:~$ qdbus $SVC /vymmodel_42 org.insilmaril.vym.model.adaptor.listCommands
Error: org.freedesktop.DBus.Error.UnknownObject
No such object path '/vymmodel_42'
```

**Comment by insilmaril** [comment]
Ah, obviously I was confused  - thanks Martin for even trying with my app :-)

Guess I am able to fix the vym-ruby.rb interface now to enable tests again.

Greetings to Praha
Uwe

**Comment by tobias-grasse** [comment]
@mvidner Thank you very much! Not only for identifying the issue (which was sitting in front of my computer 😄 ), but for the explanation as well. 
 
> I need to fix ruby-dbus so that it explains to you what you are doing wrong instead of letting the extremely unfriendly dbus-daemon handle it.

That would be a great addition, let me know if I can help out with testing given my little DBus knowledge.

**Comment by mvidner** [comment]
Now it is better. Thanks again!

## Ruby D-Bus 0.16.0 - 2019-10-15

API:
 * An invalid service name or an invalid object path will raise
   instead of being sent to the bus. The bus would then drop the connection,
   producing EOFError here (#80]).
